In [ ]:
def cal(x,y):
  add,sub,mul,div = x+y,x-y,x*y,x/y
  return add,sub,mul,div
add,sub,mul,div = cal(10,2)
print(add,sub,mul,div)

12 8 20 5.0


In [ ]:
def add_one(num):
  num += 1
  return num

num = 5
result = add_one(num)
print(result, num)

6 5


In [ ]:
def add_one():
  global num
  num += 1
  return num
num = 5
result = add_one()
print(result, num)

6 6


In [ ]:
def check_pwd(pwd):
  if pwd == '1234':
    return True
  else:
    return False

cnt = 1
while True:
  pwd = input('비밀번호 4자리 입력:  ')
  if check_pwd(pwd):
    print('Correct !')
    break
  else:
    if cnt == 5:
      print('5회 이상 시도... 프로그램 종료')
      break
    print('Try against')
  cnt += 1

비밀번호 4자리 입력:  1234
Correct !


In [ ]:
#range함수 사용법
def my_range(start = 0, stop = 10, step = 1):
  iter = [] #range()의 반환 데이터 타입을 리스트 정의

  cnt = start
  while cnt < stop:
    iter.append(cnt)
    cnt += step
  return iter

print(my_range(0,10,1))
print(my_range(1,20,2))
print(my_range())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
def my_sum(arg):
  total = 0
  for i in arg:
    total += i
  return total
print('total som : ',my_sum([1,2,3,4,5]))
print('total sum : ',my_sum((2,5,10)))#알아두기

total som :  15
total sum :  17


In [ ]:
def grade(score):
  if score >= 90:
    grade = 'A'
  elif score >= 80:
    grade = 'B'
  elif score >= 70:
    grade = 'C'
  elif score >= 60:
    grade = 'D'
  else:
    grade = 'F'
  return grade

db_score ={}
for i in range(2):
  name, score = input("stud's name? : "), int(input('score ? :'))
  score = grade(score)
  db_score[name] = score

cnt = 0
while cnt < len(db_score.keys()):
  print(list(db_score.keys())[cnt],
        list(db_score.values())[cnt])
  cnt += 1

stud's name? : 이진영
score ? :80
stud's name? : 김하겸
score ? :70
이진영 B
김하겸 C


In [ ]:
X, y = [1,2,3],[1,2.5,3.5]
hyps = [0.5,1.0,1.5]

def hyp(mat, theta):
  result = []
  for i in range(len(mat)):
    result.append(mat[i] * theta)
  return result
def cost(m,y,X):
  total = 0
  for i in range(m):
    squared_error = (y[i] - X[i]) ** 2
    total += squared_error
  return total * (1/(2*m))

for i in range(len(hyps)):
  hyp_values = hyp(X, hyps[i])

  print("Cost for", hyps[i], "is" , cost(len(X), y, hyp_values))


Cost for 0.5 is 1.0833333333333333
Cost for 1.0 is 0.08333333333333333
Cost for 1.5 is 0.25


In [ ]:
import numpy as np

X = np.array([[1],[2],[3]])
y = np.array([[1],[2.5],[3.5]])
print(X)
print(y)

thetas = np.array([[[0.,0.5]],[[0.,1.]],[[0.,1.5]]])
print(thetas)

X = np.hstack([np.ones([3,1]),X])
print(X)

def cost(X,y,theta):
  inner = np.power(((X @ theta.T)-y),2)
  return np.sum(inner) / (2*len(X))

for i in range(len(thetas)):
  print(cost(X,y,thetas[i]))



[[1]
 [2]
 [3]]
[[1. ]
 [2.5]
 [3.5]]
[[[0.  0.5]]

 [[0.  1. ]]

 [[0.  1.5]]]
[[1. 1.]
 [1. 2.]
 [1. 3.]]
1.0833333333333333
0.08333333333333333
0.25


In [ ]:
##
num = int(input('누적합계를 구할 수 를 입력: '))
s = 0

for i in range(1,num+1,1):
  s = s+i
  print('i={},s={}'.format(i,s))

누적합계를 구할 수 를 입력: 3
i=1,s=1
i=2,s=3
i=3,s=6


In [ ]:
for i in range(3):
  for j in range(3):
    print("*",end=' ')
  print('')

* * * 
* * * 
* * * 
